info:
  app:
    name: teamapp
    description: Aplicación para la gestión de equipos deportivos amateur
  build:
    goupId: @project.groupId@
    artifact: @project.artifactId@
    name: @project.name@
    version: @project.version@

server:
  port: 9091

springdoc:
  swagger-ui:
    operationsSorter: method
    path: /swagger-ui-teamapp.html

spring:
  application:
    name: Teamapp
  jpa:
    open-in-view: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    generate-ddl: true  
    hibernate:
      ddl-auto: update 
  profiles:
    active: @activeProfile@

app:
  envars:
    jwt:
      token: 9cf8baf9f21803be97a8753c0af51f10b1fd30cecb655f740f19e44fb142edf0
      expires: 2700000
    rest:
      enabled: true
