export default [
  {
    key: 'titulo',
    component: 'input',
    label: 'event.filters.fields.title.label',
    placeholder: 'event.filters.fields.title.placeholder',
    filter: {
      campo: 'titulo',
      tipo: 'string',
      comparacion: 'CONTAINS',
      expresion: null,
      joinType: null,
      entityJoinName: null,
      operador: 'AND',
      prefiltrado: false,
      filedNameCompareColumn: null,
    },
  },
  {
    key: 'ubicacion',
    component: 'input',
    label: 'event.filters.fields.location.label',
    placeholder: 'event.filters.fields.location.placeholder',
    filter: {
      campo: 'ubicacion',
      tipo: 'string',
      comparacion: 'CONTAINS',
      expresion: null,
      joinType: null,
      entityJoinName: null,
      operador: 'AND',
      prefiltrado: false,
      filedNameCompareColumn: null,
    },
  },
  {
    key: 'allDay',
    component: 'checkbox',
    label: 'event.filters.fields.allDay.label',
    checkboxLabel: 'event.filters.fields.allDay.checkbox',
    filter: {
      campo: 'allDay',
      tipo: 'boolean',
      comparacion: 'EQUALS',
      expresion: null,
      joinType: null,
      entityJoinName: null,
      operador: 'AND',
      prefiltrado: false,
      filedNameCompareColumn: null,
    },
    valueFormatter: (value) => String(value),
  },
]
