CREATE TABLE "usuario" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre" varchar NOT NULL,
  "email" varchar UNIQUE NOT NULL,
  "password" varchar,
  "created_at" timestamp,
  "modified_at" timestamp,
  "delete_at" timestamp
);

CREATE TABLE "rol" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "codigo" varchar NOT NULL,
  "descripcion" varchar
);

CREATE TABLE "equipo" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre" varchar NOT NULL,
  "descripcion" varchar,
  "created_at" timestamp,
  "modified_at" timestamp,
  "delete_at" timestamp
);

CREATE TABLE "usuario_equipo" (
  "user" bigint,
  "team" bigint,
  "rol" bigint
);

CREATE TABLE "jugador" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre" varchar NOT NULL,
  "dorsal" int,
  "posicion" bigint,
  "equipo" bigint,
  "usuario" bigint,
  "created_at" timestamp,
  "modified_at" timestamp,
  "delete_at" timestamp
);

CREATE TABLE "posicion" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "codigo" varchar UNIQUE NOT NULL,
  "descripcion" varchar,
  "created_at" timestamp,
  "modified_at" timestamp,
  "delete_at" timestamp
);

CREATE TABLE "cuota" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre" varchar NOT NULL,
  "cantidad" decimal,
  "equipo" bigint,
  "fechaFin" timestamp,
  "created_at" timestamp,
  "modified_at" timestamp,
  "delete_at" timestamp
);

CREATE TABLE "cuota_jugador" (
  "cuota" bigint,
  "jugador" bigint,
  "pagada" bool NOT NULL DEFAULT false,
  "fechaPago" timestamp
);

CREATE TABLE "noticia" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "titulo" varchar NOT NULL,
  "contenido" varchar,
  "equipo" bigint,
  "created_at" timestamp,
  "modified_at" timestamp,
  "delete_at" timestamp
);

CREATE TABLE "comentario" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "noticia" bigint,
  "jugador" bigint,
  "texto" varchar NOT NULL,
  "created_at" timestamp,
  "modified_at" timestamp,
  "delete_at" timestamp
);

CREATE TABLE "evento" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "titulo" varchar NOT NULL,
  "fechaEvento" timestamp,
  "equipo" bigint,
  "created_at" timestamp,
  "modified_at" timestamp,
  "delete_at" timestamp
);

CREATE TABLE "convocatoria" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "evento" bigint,
  "jugador" bigint,
  "asiste" bool NOT NULL DEFAULT false,
  "created_at" timestamp,
  "modified_at" timestamp,
  "delete_at" timestamp
);

CREATE TABLE "encuesta" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "titulo" varchar NOT NULL,
  "descripcion" varchar,
  "multiple" bool DEFAULT false,
  "equipo" bigint,
  "created_at" timestamp,
  "modified_at" timestamp,
  "delete_at" timestamp
);

CREATE TABLE "respuesta" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "valor" bool NOT NULL DEFAULT false,
  "jugador" bigint,
  "encuesta" bigint,
  "created_at" timestamp,
  "modified_at" timestamp,
  "delete_at" timestamp
);

CREATE INDEX "usuario_email" ON "usuario" ("email");

ALTER TABLE "usuario_equipo" ADD FOREIGN KEY ("user") REFERENCES "usuario" ("id");

ALTER TABLE "usuario_equipo" ADD FOREIGN KEY ("team") REFERENCES "equipo" ("id");

ALTER TABLE "usuario_equipo" ADD FOREIGN KEY ("rol") REFERENCES "rol" ("id");

ALTER TABLE "jugador" ADD FOREIGN KEY ("posicion") REFERENCES "posicion" ("id");

ALTER TABLE "jugador" ADD FOREIGN KEY ("equipo") REFERENCES "equipo" ("id");

ALTER TABLE "jugador" ADD FOREIGN KEY ("usuario") REFERENCES "usuario" ("id");

ALTER TABLE "cuota" ADD FOREIGN KEY ("equipo") REFERENCES "equipo" ("id");

ALTER TABLE "cuota_jugador" ADD FOREIGN KEY ("cuota") REFERENCES "cuota" ("id");

ALTER TABLE "cuota_jugador" ADD FOREIGN KEY ("jugador") REFERENCES "jugador" ("id");

ALTER TABLE "noticia" ADD FOREIGN KEY ("equipo") REFERENCES "equipo" ("id");

ALTER TABLE "comentario" ADD FOREIGN KEY ("noticia") REFERENCES "noticia" ("id");

ALTER TABLE "comentario" ADD FOREIGN KEY ("jugador") REFERENCES "jugador" ("id");

ALTER TABLE "evento" ADD FOREIGN KEY ("equipo") REFERENCES "equipo" ("id");

ALTER TABLE "convocatoria" ADD FOREIGN KEY ("evento") REFERENCES "evento" ("id");

ALTER TABLE "convocatoria" ADD FOREIGN KEY ("jugador") REFERENCES "jugador" ("id");

ALTER TABLE "encuesta" ADD FOREIGN KEY ("equipo") REFERENCES "equipo" ("id");

ALTER TABLE "respuesta" ADD FOREIGN KEY ("jugador") REFERENCES "jugador" ("id");

ALTER TABLE "respuesta" ADD FOREIGN KEY ("encuesta") REFERENCES "encuesta" ("id");
